language: node_js
node_js:
  - 8

before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1
  - npm install -g @angular/cli

install:
  - npm install

before_script:
  - greenkeeper-lockfile-update

script:
  - ng build --prod

after_script:
  - greenkeeper-lockfile-upload